### ISSUE TITLE
Trying to configure for Neovim

### ISSUE THREAD

**Issue by PMassicotte** [dgkf/debugadapter#14]
I am trying to configure this with Neovim. After reading and searching around, I came up with this configuration:

```lua
return {
  -- NOTE: Yes, you can install new plugins here!
  'mfussenegger/nvim-dap',
  -- NOTE: And you can specify dependencies as well
  dependencies = {
    -- Creates a beautiful debugger UI
    'rcarriga/nvim-dap-ui',

    -- Installs the debug adapters for you
    'williamboman/mason.nvim',
    'jay-babu/mason-nvim-dap.nvim',

    -- Add your own debuggers here
    'leoluz/nvim-dap-go',
  },
  config = function()
    local dap = require 'dap'
    local dapui = require 'dapui'

    dap.adapters.r = {
      type = 'server',
      port = 18722, -- needs to match `debugadapter::run()`'s `port` argument
    }

    dap.configurations.r = {
      {
        type = 'r',
        requests = 'attach',
        name = 'Attach session'
      }
    }
...
```

Then, I set a breakpoint, and run:

```r
debugadapter::run()
```

However, I am getting this error when I try to launch  the debugger (see the error message at the bottom of the screenshot):

![image](https://github.com/dgkf/debugadapter/assets/4519221/d7d14551-972e-4778-98bd-7e4cc87ded93)

Is there anything obvious I am missing out?

Thank you!

**Comment by joscani** [comment]
I have the same issue . I don't know how to fix it

**Comment by dgkf** [comment]
Thanks for filing, and sorry for not following up earlier.  I've mostly moved to using `helix`, so my `nvim` chops might be a bit outdated. 

Is it possible that there is a typo here?

```diff
dap.configurations.r = {
      {
        type = 'r',
-       requests = 'attach',
+       request = 'attach',
        name = 'Attach session'
      }
    }
```

I've been pretty limited on time, and unfortunately this project takes a lot of energy to jump into so it's usually one of the first that I pull back from. Just for your awareness, the implementation is _VERY_ incomplete, so even if you get it working you shouldn't expect it to be terribly useful. 

That said, if you're looking to get it working because you'd like to contribute I'd be happy to get you up to speed. 

If you'd like to see this work move forward, next steps in my eyes are 1) contributing a pre-task callback to R's internals and 2) migrating the tool to use S7 instead of its own little data-validated stateful S3 classes. The S7 data validation, state handling and multiple dispatch would clean up a lot of the code base.

**Comment by dgkf** [comment]
Going to close as this is now outdated. See `SETUP.md` for more recent discussion on configuring `neovim`. 

Note to anyone stumbling on this - we also discovered that the current R devel doesn't play nicely with `R.nvim`'s bundled R package, so to play nicely with `R.nvim`, you might have to wait until these browser hooks are stabilized into an R release.
