### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by sebffischer** [dgkf/debugadapter#9]
So I have now some understanding of the code base, and I would like to start working on adding some missing parts. 

In general, the communication between the dap-client and the r debugadapter seems to be set up, correct?
So as far as I can tell, the next steps would be to implement the concrete requests that the dap-client sends to the debugadapter. From your comments, the TODOs seem to be: 

* [ ] handle restarts
* [ ] handle suspend
* [ ] handle set function breakpoints
* [ ] handle set exception breakpoints
* [ ] handle multiline input

Are there any other changes that woud have to be made, before working on these issues makes sense? And are you already working on those issues or would you welcome contributions to these tasks?

**Comment by sebffischer** [comment]
Also, what do you think of representing the debug adapter as an R6 class?

**Comment by sebffischer** [comment]
Also I would have the question on how you intend to set up the unit tests. 

I hope I am not too intrusive here. If you prefer on working on the project yourself or whatever, please let me know!

**Comment by dgkf** [comment]
@sebffischer - Love the enthusiasm here! Thanks so much for combing through the code. I was planning to draft some todo's today to help with onboarding, but you've really jumped right in. 

> In general, the communication between the dap-client and the r debugadapter seems to be set up, correct?

Correct... mostly. Relaying information back from the R debug browser to the debugadapter is still a WIP. Noted in ALL CAPS below, there are two architectures that I've been experimenting with for this. I'm leaning toward option A since it minimizes the need to juggle tcp connections to the server process.

```mermaid
flowchart LR

repl[fa:fa-terminal R Session]
browser[Shadow Browser]
server[DAP Server]
client[DAP Client]

subgraph R Session
    server -->|<i>tcp socket</i> <br> debugger <br> breakpoint <br>messages| repl
    repl -->|"<i>stdin</i> <br> browser() commands"| browser
    browser -->|"<i>stderr</i> <br> browser() output"| repl

    browser -->|"<i>tcp socket</i> <br> OPTION A: RELAY THROUGH REPL "| repl
    repl -->|"<i>tcp socket</i> <br> OPTION A: RELAY THROUGH REPL "| server

    browser -->|"<i>tcp socket</i> <br> OPTION B: DIRECT TO ADAPTER "| server

    subgraph fork[Forked <br> Process]
        browser
    end

    subgraph bg[Background <br> Process]
        server
    end
end

subgraph IDE
    client
end

client --->|<i>tcp socket</i> <br> requests| server
server --->|"<i>tcp socket</i> <br> responses"| client
```

This is my current priority. 

I have some draft code starting to implement this, but I haven't been completely happy with how the architecture is coming together so it's been living in draft for a while. I'll get it pushed up into a branch so that you can see how I'm thinking about approaching it.

> Also, what do you think of representing the debug adapter as an R6 class?

I generally want to keep the architecture functional and minimal on mutable internal state. I find functional behaviors far easier to reason about and implement. My hypothesis is that a debugadapter translates well to this style since any state is captured by the environment at each debug step and theoretically shouldn't need to be stored otherwise. 

That said, there's one bit of global state that needs to be stored and passed around with an adapter - the breakpoints. I think that representing the breakpoints might be a good use case. If we do go down that path, I'd like to keep the R6 internal state as minimal as possible, for example keeping a surface level debugadapter S3 structure that includes an R6 breakpoints object. 

I'm overall not opposed to any of it growing into an R6 class if the protocol necessitates it, but I see it as a last resort only to be used when mutable state is needed.

> Also I would have the question on how you intend to set up the unit tests.

Great question :sweat_smile:. With a lot of inter-process communication this is inherently a tough thing to test. I think there are a few places where testing is more immediately actionable:

- Receiving and responding to individual messages, which can be done by mocking messages from the server and testing replies entirely in a single process test.
- Testing the _shadow browser_ - A bit harder to test since it deliberately intercepts file handles on the running process, but I see this as a challenging bit of code that necessitates testing
- Testing running debug adapters (in the current or background process) - I think these need to be tested in a separate R process, where a connection can be formed by the process running the tests and messages can be sent by mocking a server as full integration-style tests.

**Comment by sebffischer** [comment]
Thanks for the elaborate response! I will check out the branch and continue combing through the code.

**Comment by dgkf** [comment]
I'm going to close this as the project is in a very different place now. I'll do my best to file more granular issues for things that I think can be good next steps now that the path forward feels a little more certain.
